version: '3'
services:
  server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3001"
    networks:
      - youpip
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodata:/data/db
    networks:
      - youpip
volumes:
  mongodata:

networks:
  youpip:
    driver: bridge
